version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: ai_support_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongodb_data:/data/db
    networks:
      - ai_support_network

  backend:
    build: ./backend
    container_name: ai_support_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - MONGODB_URL=mongodb://admin:password123@mongodb:27017
      - DATABASE_NAME=customer_support
      - ELEVENLABS_VOICE_ID=21m00Tcm4TlvDq8ikWAM
    volumes:
      - ./backend/audio_files:/app/audio_files
    depends_on:
      - mongodb
    networks:
      - ai_support_network

  frontend:
    build: ./frontend
    container_name: ai_support_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - ai_support_network

volumes:
  mongodb_data:

networks:
  ai_support_network:
    driver: bridge
